server:
  port: 8088
spring:
# 数据库配置
  datasource:
#    test1:
#      driver-class-name: dm.jdbc.driver.DmDriver
#      url: jdbc:dm://172.18.151.35:5236?useUnicode=true&useSSL=false&characterEncoding=utf8
#      username: LICENCE_AUTH
#      password: cntrust123
#    test2:
#      driver-class-name: dm.jdbc.driver.DmDriver
#      url: jdbc:dm://172.18.151.35:5236?useUnicode=true&useSSL=false&characterEncoding=utf8
#      username: LICENCE_AUTH
#      password: cntrust123
#
    driver-class-name: dm.jdbc.driver.DmDriver
#    url: jdbc:dm://172.18.151.35:5236?useUnicode=true&useSSL=false&characterEncoding=utf8

    url: jdbc:dm://192.168.99.35:5236?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: LICENCE_APP
    password: cntrust123
  servlet:
    multipart:
      enabled: true
      resolve-lazily: true
      max-file-size: 10MB
#    hikari:
#      maximum-pool-size:
#      metrics-tracker-factory:
mybatis:
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.wjl.testdata.entity
  mapper-locations: classpath:/mapper/*.xml
#spring:
